name: 'ci'

on: ['push', 'pull_request']

jobs:
  check:
    name: 'Check JavaScript code'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Install Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Install depedendencies without building'
        run: npm ci --ignore-scripts

      - name: 'Lint'
        run: npm run lint

  build:
    name: 'Build binaries on ${{ matrix.os }} ${{ matrix.arch }}'
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [Ubuntu, Windows, macOS]
        arch: [x64]
        include:
          - os: Windows
            arch: x86

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Install Node.js ${{ matrix.arch }}'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          architecture: ${{ matrix.arch }}

      - name: 'Install Linux dependencies'
        if: ${{ matrix.os == 'Ubuntu' }}
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev

      - name: 'Install dependencies and build from source'
        run: npm ci --build-from-source

      - name: 'Build binaries for all ABIs'
        run: npm run prebuild

      - name: 'Upload prebuilt binaries'
        uses: actions/upload-artifact@v2
        with:
          name: prebuilds-${{ matrix.os }}-${{ matrix.arch }}
          path: prebuilds

  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: 'Publish release'
    needs: [check, build]
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Install Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Install depedendencies without building'
        run: npm ci --ignore-scripts

      - name: 'Download prebuilt binaries'
        uses: actions/download-artifact@v2
        with:
          path: prebuilds

      # TODO
      # - name: 'Publish to npm'
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Upload prebuilt artifacts to GitHub release'
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: npm run prebuild-upload -- ${{ secrets.GITHUB_TOKEN }}
